-- V020 — identity/workspace foundation for G4.2.
-- V017 created Better Auth's native "user" table plus compatibility-shaped
-- memberships/invites. This migration converts those two tables to the target
-- UUID/FK model without discarding their existing rows.

CREATE TABLE IF NOT EXISTS households (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'shared',
    CONSTRAINT households_kind_chk CHECK (kind IN ('personal', 'shared')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE households ADD COLUMN IF NOT EXISTS kind TEXT;
UPDATE households SET kind = 'shared' WHERE kind IS NULL;
ALTER TABLE households ALTER COLUMN kind SET DEFAULT 'shared';
ALTER TABLE households ALTER COLUMN kind SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'households_kind_chk'
  ) THEN
    ALTER TABLE households
      ADD CONSTRAINT households_kind_chk CHECK (kind IN ('personal', 'shared'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id  TEXT UNIQUE REFERENCES "user" (id) ON DELETE CASCADE,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'disabled')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Legacy deployments may already contain an empty users table with a
-- different shape. Upgrade that table in place; populated rows without an
-- email cannot be safely mapped to Better Auth and must stop the migration.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS auth_user_id TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM users WHERE email IS NULL) THEN
    RAISE EXCEPTION 'legacy users rows require an email before identity migration';
  END IF;
END $$;

ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users ALTER COLUMN status SET NOT NULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_status_chk') THEN
    ALTER TABLE users
      ADD CONSTRAINT users_status_chk CHECK (status IN ('active', 'disabled'));
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS users_email_uidx ON users (email);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_auth_user_id_key') THEN
    ALTER TABLE users ADD CONSTRAINT users_auth_user_id_key UNIQUE (auth_user_id);
  END IF;
END $$;

-- Preserve existing Better Auth identities in the application identity table.
INSERT INTO users (auth_user_id, email, name, status, created_at)
SELECT id, email, name, 'active', "createdAt"
  FROM "user"
ON CONFLICT (auth_user_id) DO UPDATE
  SET email = EXCLUDED.email, name = EXCLUDED.name;

-- The production baseline has financial tables with household_id but no
-- households table. Materialize every existing financial household first;
-- preexisting names remain untouched when a row already exists.
INSERT INTO households (id, name, kind)
SELECT household_id, 'Migrated household', 'shared' FROM accounts
UNION
SELECT household_id, 'Migrated household', 'shared' FROM categories
UNION
SELECT household_id, 'Migrated household', 'shared' FROM transactions
ON CONFLICT (id) DO NOTHING;

-- V017 membership rows use Better Auth text IDs. Rebuild the table with the
-- target UUID user FK while preserving role, household and creation time.
INSERT INTO households (id, name, kind)
SELECT household_id, 'Migrated household', 'shared'
  FROM memberships
ON CONFLICT (id) DO NOTHING;

CREATE TABLE memberships_v020 (
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    household_id UUID NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    role         TEXT NOT NULL CHECK (role IN ('owner', 'member')),
    status       TEXT NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'removed')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, household_id)
);

INSERT INTO memberships_v020 (user_id, household_id, role, status, created_at)
SELECT u.id, m.household_id, m.role, 'active', m.created_at
  FROM memberships m
  JOIN users u ON u.auth_user_id = m.user_id;

DROP TABLE memberships;
ALTER TABLE memberships_v020 RENAME TO memberships;
CREATE INDEX memberships_household_status_idx ON memberships (household_id, status);

-- Invite IDs generated by V017 are UUID strings. Keep their hashes, expiry,
-- normalized email and consumption timestamp while changing both relationships
-- to UUID FKs. invited_by stays nullable to preserve old SET NULL semantics.
INSERT INTO households (id, name, kind)
SELECT household_id, 'Migrated household', 'shared'
  FROM invites
ON CONFLICT (id) DO NOTHING;

CREATE TABLE invites_v020 (
    id             UUID PRIMARY KEY,
    household_id   UUID NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    email          TEXT NOT NULL,
    email_normalized TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('owner', 'member')),
    token_hash     TEXT NOT NULL UNIQUE,
    expires_at     TIMESTAMPTZ NOT NULL,
    consumed_at    TIMESTAMPTZ,
    invited_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO invites_v020 (
    id, household_id, email, email_normalized, role, token_hash,
    expires_at, consumed_at, invited_by, created_at
)
SELECT i.id::uuid, i.household_id, i.email, i.email_normalized, i.role,
       i.token_hash, i.expires_at, i.accepted_at, u.id, i.created_at
  FROM invites i
  LEFT JOIN users u ON u.auth_user_id = i.invited_by_user_id;

DROP TABLE invites;
ALTER TABLE invites_v020 RENAME TO invites;
CREATE INDEX invites_household_idx ON invites (household_id);
CREATE INDEX invites_email_normalized_idx ON invites (email_normalized);
