export type RouteMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'ALL';
export type RouteAuth = 'public' | 'public-denied' | 'device' | 'workspace' | 'session';
export type RouteOwnership = 'none' | 'membership' | 'owner';

export type RouteInventoryEntry = {
  id: string;
  method: RouteMethod;
  path: string;
  auth: RouteAuth;
  ownership: RouteOwnership;
};

/** Canonical authz inventory. Add a test ID whenever a route is added. */
export const ROUTE_INVENTORY: readonly RouteInventoryEntry[] = [
  { id: 'auth-provider', method: 'ALL', path: '/auth/*', auth: 'public', ownership: 'none' },
  { id: 'auth-invites-create', method: 'POST', path: '/auth/invites', auth: 'session', ownership: 'owner' },
  { id: 'auth-invites-accept', method: 'POST', path: '/auth/invites/accept', auth: 'session', ownership: 'none' },
  { id: 'auth-reconnect', method: 'POST', path: '/auth/reconnect', auth: 'public', ownership: 'none' },
  { id: 'auth-reconnect-token', method: 'POST', path: '/auth/reconnect-token', auth: 'session', ownership: 'none' },
  { id: 'auth-devices-me', method: 'GET', path: '/auth/devices/me', auth: 'device', ownership: 'none' },
  { id: 'auth-devices-register', method: 'POST', path: '/auth/devices/register', auth: 'public-denied', ownership: 'none' },
  { id: 'auth-devices-revoke', method: 'POST', path: '/auth/devices/revoke', auth: 'device', ownership: 'none' },
  { id: 'workspaces-list', method: 'GET', path: '/workspaces', auth: 'session', ownership: 'none' },
  { id: 'workspaces-create', method: 'POST', path: '/workspaces', auth: 'session', ownership: 'none' },
  { id: 'workspace-members-list', method: 'GET', path: '/workspaces/:householdId/members', auth: 'session', ownership: 'membership' },
  { id: 'workspace-member-remove', method: 'DELETE', path: '/workspaces/:householdId/members/:userId', auth: 'session', ownership: 'owner' },
  { id: 'workspace-leave', method: 'POST', path: '/workspaces/:householdId/leave', auth: 'session', ownership: 'membership' },
  { id: 'ownership-transfer-create', method: 'POST', path: '/workspaces/:householdId/ownership-transfers', auth: 'workspace', ownership: 'owner' },
  { id: 'ownership-transfer-accept', method: 'POST', path: '/workspaces/:householdId/ownership-transfers/:transferId/accept', auth: 'workspace', ownership: 'membership' },
  { id: 'accounts-list', method: 'GET', path: '/accounts', auth: 'workspace', ownership: 'membership' },
  { id: 'accounts-details', method: 'GET', path: '/accounts/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'accounts-create', method: 'POST', path: '/accounts', auth: 'workspace', ownership: 'membership' },
  { id: 'accounts-update', method: 'PATCH', path: '/accounts/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'accounts-deactivate', method: 'POST', path: '/accounts/:id/deactivate', auth: 'workspace', ownership: 'membership' },
  { id: 'audit-logs-list', method: 'GET', path: '/audit-logs', auth: 'workspace', ownership: 'membership' },
  { id: 'budgets-list', method: 'GET', path: '/budgets', auth: 'workspace', ownership: 'membership' },
  { id: 'budgets-create', method: 'POST', path: '/budgets', auth: 'workspace', ownership: 'membership' },
  { id: 'budgets-update', method: 'PATCH', path: '/budgets/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'budgets-check', method: 'GET', path: '/budgets/check', auth: 'workspace', ownership: 'membership' },
  { id: 'budgets-trends', method: 'GET', path: '/budgets/:id/trends', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-accounts', method: 'GET', path: '/cards/accounts', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-statements', method: 'GET', path: '/cards/statements', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-statement-details', method: 'GET', path: '/cards/statements/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-purchases-create', method: 'POST', path: '/cards/purchases', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-installments-create', method: 'POST', path: '/cards/installments', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-recurring-list', method: 'GET', path: '/cards/recurring', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-recurring-create', method: 'POST', path: '/cards/recurring', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-statement-pay', method: 'POST', path: '/cards/statements/:id/pay', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-create', method: 'POST', path: '/cards', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-update', method: 'PATCH', path: '/cards/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'cards-purchase-update', method: 'PATCH', path: '/cards/purchases/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'categories-list', method: 'GET', path: '/categories', auth: 'workspace', ownership: 'membership' },
  { id: 'categories-create', method: 'POST', path: '/categories', auth: 'workspace', ownership: 'membership' },
  { id: 'categories-update', method: 'PATCH', path: '/categories/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'categories-deactivate', method: 'POST', path: '/categories/:id/deactivate', auth: 'workspace', ownership: 'membership' },
  { id: 'dashboard-summary', method: 'GET', path: '/dashboard/summary', auth: 'workspace', ownership: 'membership' },
  { id: 'dashboard-month-summary', method: 'GET', path: '/dashboard/month-summary', auth: 'workspace', ownership: 'membership' },
  { id: 'goals-list', method: 'GET', path: '/goals', auth: 'workspace', ownership: 'membership' },
  { id: 'goals-create', method: 'POST', path: '/goals', auth: 'workspace', ownership: 'membership' },
  { id: 'goals-contribute', method: 'POST', path: '/goals/:id/contribute', auth: 'workspace', ownership: 'membership' },
  { id: 'goals-cancel', method: 'POST', path: '/goals/:id/cancel', auth: 'workspace', ownership: 'membership' },
  { id: 'goals-update', method: 'PATCH', path: '/goals/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-list', method: 'GET', path: '/payables', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-create', method: 'POST', path: '/payables', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-pay', method: 'POST', path: '/payables/:id/pay', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-unpay', method: 'POST', path: '/payables/:id/unpay', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-update', method: 'PATCH', path: '/payables/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-cancel', method: 'POST', path: '/payables/:id/cancel', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-templates-list', method: 'GET', path: '/payables/templates', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-templates-create', method: 'POST', path: '/payables/templates', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-from-template', method: 'POST', path: '/payables/from-template', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-auto-create-from-templates', method: 'POST', path: '/payables/auto-create-from-templates', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-refresh-status', method: 'POST', path: '/payables/refresh-status', auth: 'workspace', ownership: 'membership' },
  { id: 'payables-reminders', method: 'GET', path: '/payables/reminders', auth: 'workspace', ownership: 'membership' },
  { id: 'notifications-list', method: 'GET', path: '/notifications', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-list', method: 'GET', path: '/pending-operations', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-details-dual', method: 'GET', path: '/pending-operations/details', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-details', method: 'GET', path: '/pending-operations/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-approve-dual', method: 'POST', path: '/pending-operations/approve', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-approve', method: 'POST', path: '/pending-operations/:id/approve', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-reject-dual', method: 'POST', path: '/pending-operations/reject', auth: 'workspace', ownership: 'membership' },
{ id: 'pending-operations-reject', method: 'POST', path: '/pending-operations/:id/reject', auth: 'workspace', ownership: 'membership' },
  { id: 'pending-operations-undo', method: 'POST', path: '/pending-operations/undo', auth: 'workspace', ownership: 'membership' },
  { id: 'notifications-create', method: 'POST', path: '/notifications', auth: 'workspace', ownership: 'membership' },
  { id: 'adoption-events-create', method: 'POST', path: '/observability/adoption-events', auth: 'workspace', ownership: 'membership' },
  { id: 'adoption-funnel-get', method: 'GET', path: '/observability/adoption-funnel', auth: 'workspace', ownership: 'membership' },
  { id: 'insights-quick', method: 'GET', path: '/insights/quick', auth: 'workspace', ownership: 'membership' },
  { id: 'insights-spending', method: 'GET', path: '/insights/spending', auth: 'workspace', ownership: 'membership' },
  { id: 'profile-get', method: 'GET', path: '/profile', auth: 'workspace', ownership: 'membership' },
  { id: 'push-vapid-public-key', method: 'GET', path: '/push/vapid-public-key', auth: 'workspace', ownership: 'membership' },
  { id: 'push-subscriptions-create', method: 'POST', path: '/push/subscriptions', auth: 'workspace', ownership: 'membership' },
  { id: 'push-notifications-send', method: 'POST', path: '/push/notifications', auth: 'workspace', ownership: 'membership' },
  { id: 'push-subscriptions-delete', method: 'DELETE', path: '/push/subscriptions', auth: 'workspace', ownership: 'membership' },
  { id: 'profile-update', method: 'PATCH', path: '/profile', auth: 'workspace', ownership: 'membership' },
  { id: 'subscriptions-list', method: 'GET', path: '/subscriptions', auth: 'workspace', ownership: 'membership' },
  { id: 'subscriptions-create', method: 'POST', path: '/subscriptions', auth: 'workspace', ownership: 'membership' },
  { id: 'subscriptions-cancel', method: 'POST', path: '/subscriptions/:id/cancel', auth: 'workspace', ownership: 'membership' },
  { id: 'subscriptions-update', method: 'PATCH', path: '/subscriptions/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'transactions-list', method: 'GET', path: '/transactions', auth: 'workspace', ownership: 'membership' },
  { id: 'transactions-expense-create', method: 'POST', path: '/transactions/expense', auth: 'workspace', ownership: 'membership' },
  { id: 'transactions-income-create', method: 'POST', path: '/transactions/income', auth: 'workspace', ownership: 'membership' },
  { id: 'transfers-create', method: 'POST', path: '/transfers', auth: 'workspace', ownership: 'membership' },
  { id: 'transactions-update', method: 'PATCH', path: '/transactions/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'transactions-delete', method: 'DELETE', path: '/transactions/:id', auth: 'workspace', ownership: 'membership' },
  { id: 'shadow-divergence-record', method: 'POST', path: '/observability/shadow-divergence', auth: 'workspace', ownership: 'membership' },
  { id: 'shadow-divergence-summary', method: 'GET', path: '/observability/shadow-divergence/summary', auth: 'workspace', ownership: 'membership' },
  { id: 'shadow-divergence-events', method: 'GET', path: '/observability/shadow-divergence/events', auth: 'workspace', ownership: 'membership' },
  { id: 'health', method: 'GET', path: '/health', auth: 'public', ownership: 'none' },
] as const;

export const ROUTE_COVERAGE_IDS = [
  'auth-provider', 'auth-invites-create', 'auth-invites-accept', 'auth-reconnect', 'auth-reconnect-token', 'auth-devices-me', 'auth-devices-register', 'auth-devices-revoke',
  'workspaces-list', 'workspaces-create', 'workspace-members-list', 'workspace-member-remove', 'workspace-leave',
  'ownership-transfer-create', 'ownership-transfer-accept', 'accounts-list', 'accounts-details', 'accounts-create', 'accounts-update', 'accounts-deactivate',
  'audit-logs-list', 'budgets-list', 'budgets-create', 'budgets-update', 'budgets-check', 'budgets-trends', 'cards-accounts',
  'cards-statements', 'cards-statement-details', 'cards-purchases-create', 'cards-installments-create', 'cards-recurring-list', 'cards-recurring-create',
  'cards-statement-pay', 'cards-create', 'cards-update', 'cards-purchase-update', 'categories-list', 'categories-create',
  'categories-update', 'categories-deactivate', 'dashboard-summary', 'dashboard-month-summary', 'goals-list', 'goals-create',
  'goals-contribute', 'goals-cancel', 'goals-update', 'payables-list', 'payables-create', 'payables-pay', 'payables-unpay',
  'payables-update', 'payables-cancel', 'payables-templates-list', 'payables-templates-create', 'payables-from-template', 'payables-auto-create-from-templates', 'payables-refresh-status',
  'payables-reminders', 'notifications-list', 'pending-operations-list', 'pending-operations-details-dual', 'pending-operations-details', 'pending-operations-approve-dual', 'pending-operations-approve', 'pending-operations-reject-dual', 'pending-operations-reject', 'pending-operations-undo', 'notifications-create', 'adoption-events-create', 'adoption-funnel-get', 'insights-quick', 'insights-spending', 'profile-get',
  'profile-update', 'push-vapid-public-key', 'push-subscriptions-create', 'push-notifications-send', 'push-subscriptions-delete', 'subscriptions-list', 'subscriptions-create', 'subscriptions-cancel', 'subscriptions-update', 'transactions-list',
  'transactions-expense-create', 'transactions-income-create', 'transfers-create', 'transactions-update', 'transactions-delete',
  'shadow-divergence-record', 'shadow-divergence-summary', 'shadow-divergence-events', 'health',
] as const;

