import type {
  Account,
  Category,
  Transaction,
  Payable,
  Budget,
  Goal,
  Debt,
  Subscription,
} from "./types";

export const mockAccounts: Account[] = [
  {
    id: "acc1",
    name: "Nubank",
    balanceCents: 154320,
    kind: "checking",
    color: "#820AD1",
  },
  {
    id: "acc2",
    name: "Itaú",
    balanceCents: 2890,
    kind: "checking",
    color: "#EC7000",
  },
  {
    id: "acc3",
    name: "Inter",
    balanceCents: 50000,
    kind: "savings",
    color: "#FF7A00",
  },
  {
    id: "acc4",
    name: "Nubank Crédito",
    balanceCents: 0,
    kind: "credit_card",
    creditLimitCents: 1200000,
    closingDay: 15,
    dueDay: 22,
    color: "#820AD1",
  },
  {
    id: "acc5",
    name: "Inter Mastercard",
    balanceCents: 0,
    kind: "credit_card",
    creditLimitCents: 800000,
    closingDay: 10,
    dueDay: 18,
    color: "#FF7A00",
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat1",
    name: "Alimentação",
    kind: "expense",
    icon: "UtensilsCrossed",
    subcategories: ["Mercado", "Restaurante", "Ifood"],
  },
  {
    id: "cat2",
    name: "Transporte",
    kind: "expense",
    icon: "Car",
    subcategories: ["Gasolina", "Uber", "Estacionamento"],
  },
  { id: "cat3", name: "Moradia", kind: "expense", icon: "Home" },
  { id: "cat4", name: "Saúde", kind: "expense", icon: "Heart" },
  { id: "cat5", name: "Salário", kind: "income", icon: "DollarSign" },
  { id: "cat6", name: "Freelas", kind: "income", icon: "Laptop" },
];

export const mockTransactions: Transaction[] = [
  {
    id: "tx1",
    description: "Supermercado Extra",
    amountCents: 28750,
    date: "2026-06-20",
    kind: "expense",
    categoryId: "cat1",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx2",
    description: "Uber para casa",
    amountCents: 1890,
    date: "2026-06-19",
    kind: "expense",
    categoryId: "cat2",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx3",
    description: "Salário Junho",
    amountCents: 570000,
    date: "2026-06-05",
    kind: "income",
    categoryId: "cat5",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx4",
    description: "Aluguel",
    amountCents: 180000,
    date: "2026-06-01",
    kind: "expense",
    categoryId: "cat3",
    accountId: "acc2",
    method: "TED",
  },
  {
    id: "tx5",
    description: "Farmácia Paguem",
    amountCents: 8900,
    date: "2026-06-18",
    kind: "expense",
    categoryId: "cat4",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx6",
    description: "Freela Site",
    amountCents: 85000,
    date: "2026-06-10",
    kind: "income",
    categoryId: "cat6",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx7",
    description: "Conta de luz",
    amountCents: 22000,
    date: "2026-06-15",
    kind: "expense",
    categoryId: "cat3",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx8",
    description: "Internet fibra",
    amountCents: 12990,
    date: "2026-06-12",
    kind: "expense",
    categoryId: "cat3",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx9",
    description: "Pix para Maria",
    amountCents: 15000,
    date: "2026-06-17",
    kind: "transfer",
    categoryId: "cat3",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx10",
    description: "Ifood",
    amountCents: 4500,
    date: "2026-06-21",
    kind: "expense",
    categoryId: "cat6",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx11",
    description: "PIX para Nubank",
    amountCents: 50000,
    date: "2026-06-08",
    kind: "transfer",
    categoryId: "cat3",
    accountId: "acc1",
    method: "PIX",
  },
  {
    id: "tx12",
    description: "Venda app",
    amountCents: 30000,
    date: "2026-06-14",
    kind: "income",
    categoryId: "cat6",
    accountId: "acc1",
    method: "PIX",
  },
];

// Card purchases added separately (different descriptions to avoid test conflicts)
export const mockTransactionsCardPurchases: Transaction[] = [
  {
    id: "tx13",
    description: "App Store",
    amountCents: 1990,
    date: "2026-06-10",
    kind: "expense",
    categoryId: "cat6",
    accountId: "acc4",
    method: "PIX",
  },
  {
    id: "tx14",
    description: "Google Play",
    amountCents: 2190,
    date: "2026-06-15",
    kind: "expense",
    categoryId: "cat6",
    accountId: "acc4",
    method: "PIX",
  },
  {
    id: "tx15",
    description: "iFood",
    amountCents: 18750,
    date: "2026-06-12",
    kind: "expense",
    categoryId: "cat6",
    accountId: "acc5",
    method: "PIX",
  },
];

// Full transactions array = core + card purchases
export const ALL_MOCK_TRANSACTIONS: Transaction[] = [
  ...mockTransactions,
  ...mockTransactionsCardPurchases,
];

export const mockPayables: Payable[] = [
  {
    id: "p1",
    description: "Aluguel",
    amountCents: 180000,
    dueDate: "2026-07-01",
    status: "pending",
  },
  {
    id: "p2",
    description: "Luz",
    amountCents: 22000,
    dueDate: "2026-06-20",
    status: "pending",
  },
  {
    id: "p3",
    description: "Internet",
    amountCents: 12090,
    dueDate: "2026-06-22",
    status: "pending",
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "bud1",
    categoryId: "cat1",
    name: "Alimentação",
    amountCents: 50000,
    spentCents: 29200,
    period: "monthly",
  },
  {
    id: "bud2",
    categoryId: "cat2",
    name: "Transporte",
    amountCents: 15000,
    spentCents: 3720,
    period: "monthly",
  },
  {
    id: "bud3",
    categoryId: "cat5",
    name: "Salário",
    amountCents: 600000,
    spentCents: 540000,
    period: "monthly",
  },
];

export const mockDebts: Debt[] = [
  {
    id: "d1",
    name: "Financiamento Carro",
    totalAmountCents: 4800000,
    paidAmountCents: 1200000,
    interestRate: 0.015,
    installmentsTotal: 48,
    installmentsPaid: 12,
    startDate: "2025-06-01",
  },
  {
    id: "d2",
    name: "Curso Online",
    totalAmountCents: 240000,
    paidAmountCents: 60000,
    interestRate: 0,
    installmentsTotal: 12,
    installmentsPaid: 3,
    startDate: "2026-03-01",
  },
];

export const mockGoals: Goal[] = [
  {
    id: "g1",
    name: "Reserva de emergência",
    goalType: "emergency_fund",
    targetAmountCents: 600000,
    currentAmountCents: 150000,
  },
  {
    id: "g2",
    name: "Viagem fim de ano",
    goalType: "savings",
    targetAmountCents: 300000,
    currentAmountCents: 80000,
    targetDate: "2026-12-01",
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub1",
    name: "Netflix",
    amountCents: 5590,
    cycle: "monthly",
    day: 15,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub2",
    name: "Spotify",
    amountCents: 2100,
    cycle: "monthly",
    day: 5,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub3",
    name: "Amazon Prime",
    amountCents: 1580,
    cycle: "monthly",
    day: 20,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub4",
    name: "Disney+",
    amountCents: 4590,
    cycle: "monthly",
    day: 10,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub5",
    name: "Azure",
    amountCents: 29900,
    cycle: "monthly",
    day: 1,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub6",
    name: "YouTube Premium",
    amountCents: 2590,
    cycle: "monthly",
    day: 12,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub7",
    name: "ChatGPT Plus",
    amountCents: 5900,
    cycle: "monthly",
    day: 3,
    paymentMethod: "Nubank",
    status: "active",
  },
  {
    id: "sub8",
    name: "Vivo Internet",
    amountCents: 9990,
    cycle: "monthly",
    day: 8,
    paymentMethod: "Itaú",
    status: "cancelled",
  },
];
