/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false worker-configuration.generated.d.ts` (hash: 40cf755645df8fc54f8f1c3e87b26de4)
interface __BaseEnv_Env {
	API_ORIGIN: "https://api.synkroo.com.br";
	AGENT: DurableObjectNamespace<import("./src/index").WorkspaceAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN">> {}
}
