/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false worker-configuration.generated.d.ts` (hash: e83f6b4988402907968dc1a9cf9eeffb)
// T4.3 (SPEC section 11 E4): hand-updated after removing the retired legacy
// agent binding — regenerate with `wrangler types` to refresh the hash.
interface __BaseEnv_Env {
	API_ORIGIN: "https://api.synkroo.com.br";
	FINANCE_CHAT_AGENT: DurableObjectNamespace<import("./src/worker").FinanceChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "FinanceChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN">> {}
}
